In [1]:
# mentos zindagi
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('covid.csv')

In [3]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
x=df.iloc[:,0:-1]
y=df.has_covid

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
x_train.head(1)

    age  gender  fever cough    city
55   81  Female  101.0  Mild  Mumbai

In [10]:
# Column Transformers

from sklearn.compose import ColumnTransformer
#syntax
ColumnTransformer(transformers=[
    ('name','Object',['where']),
    ('name','Object',['where']),
    ('name','Object',['where']),
])

ColumnTransformer(transformers=[('name', 'Object', ['where']),
                                ('name', 'Object', ['where']),
                                ('name', 'Object', ['where'])])

In [14]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
transformer = ColumnTransformer(transformers=[
    ('trf1',SimpleImputer(strategy='mean'),['fever']),
    ('trf2',StandardScaler(),['age','fever']),
    ('trf3',OneHotEncoder(sparse_output=False,dtype=int,categories=[['Female','Male']]),['gender']),
    ('trf4',OrdinalEncoder(categories=[['Mild','Strong']],dtype=int),['cough']),
    ('trf5',OneHotEncoder(dtype=int,sparse_output=False),['city'])
],remainder='passthrough')

In [15]:
transformer

ColumnTransformer(remainder='passthrough',
                  transformers=[('trf1', SimpleImputer(), ['fever']),
                                ('trf2', StandardScaler(), ['age', 'fever']),
                                ('trf3',
                                 OneHotEncoder(categories=[['Female', 'Male']],
                                               dtype=<class 'int'>,
                                               sparse_output=False),
                                 ['gender']),
                                ('trf4',
                                 OrdinalEncoder(categories=[['Mild', 'Strong']],
                                                dtype=<class 'int'>),
                                 ['cough']),
                                ('trf5',
                                 OneHotEncoder(dtype=<class 'int'>,
                                               sparse_output=False),
                                 ['city'])])

In [16]:
transformer.fit(x_train)

ColumnTransformer(remainder='passthrough',
                  transformers=[('trf1', SimpleImputer(), ['fever']),
                                ('trf2', StandardScaler(), ['age', 'fever']),
                                ('trf3',
                                 OneHotEncoder(categories=[['Female', 'Male']],
                                               dtype=<class 'int'>,
                                               sparse_output=False),
                                 ['gender']),
                                ('trf4',
                                 OrdinalEncoder(categories=[['Mild', 'Strong']],
                                                dtype=<class 'int'>),
                                 ['cough']),
                                ('trf5',
                                 OneHotEncoder(dtype=<class 'int'>,
                                               sparse_output=False),
                                 ['city'])])

In [19]:
pd.DataFrame(transformer.transform(x_train),columns=transformer.get_feature_names_out())

,trf1__fever,trf2__age,trf2__fever,trf3__gender_Female,trf3__gender_Male,trf4__cough,trf5__city_Bangalore,trf5__city_Delhi,trf5__city_Kolkata,trf5__city_Mumbai
0,101.0,1.566141,0.000000,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,100.0,-1.558945,-0.491423,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,100.0,-0.983271,-0.491423,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,100.0,-0.654315,-0.491423,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,103.0,1.237185,0.982846,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
75,102.0,-0.777674,0.491423,1.0,0.0,1.0,1.0,0.0,0.0,0.0
76,104.0,1.319424,1.474269,1.0,0.0,1.0,0.0,1.0,0.0,0.0
77,104.0,0.332554,1.474269,0.0,1.0,0.0,1.0,0.0,0.0,0.0
78,102.0,1.607261,0.491423,1.0,0.0,1.0,0.0,0.0,1.0,0.0
79,100.0,-1.312228,-0.491423,1.0,0.0,1.0,0.0,0.0,1.0,0.0